<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_KONTAKTI</name>
   <tag></tag>
   <elementGuidId>78fba267-fc3c-4d8b-9e77-413ef2c56d36</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//nav[@id='main-nav']/div/ul/li[5]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>17e9200d-f6bd-47b1-bf0d-fa4bb5641e51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/aplikacije/kontakti/</value>
      <webElementGuid>21585673-2ccc-45f9-9f49-57cf863ae815</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>KONTAKTI</value>
      <webElementGuid>f22c6fcd-0639-4756-aee9-25eefb1574e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-nav&quot;)/div[@class=&quot;block&quot;]/ul[1]/li[5]/a[1]</value>
      <webElementGuid>fdbd48e2-28ea-493e-bb3a-ccb70668c607</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//nav[@id='main-nav']/div/ul/li[5]/a</value>
      <webElementGuid>01bfdf02-f737-46ef-8cea-f84d70243faa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'KONTAKTI')])[2]</value>
      <webElementGuid>621fced3-4e41-4e04-bccc-2935397913ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AKADEMIJA FERI'])[2]/following::a[1]</value>
      <webElementGuid>47b32be2-b1e5-44a2-be14-9494a0ef6c55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='RAZISKOVANJE'])[2]/following::a[2]</value>
      <webElementGuid>d42612d9-9e93-44d9-a532-9167f68fa743</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Zapri primarno navigacijo'])[1]/preceding::a[1]</value>
      <webElementGuid>a2d4d1e8-50a1-47fd-9cae-94628ee93e7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NOVICE'])[1]/preceding::a[2]</value>
      <webElementGuid>9305b347-7237-40f7-bd9e-9dd5a675e3b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/aplikacije/kontakti/')])[2]</value>
      <webElementGuid>05e245cf-deb4-41df-ad76-275c3db302a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/nav/div/ul/li[5]/a</value>
      <webElementGuid>cc8e0466-4621-4a9c-930f-fc273ce686a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/aplikacije/kontakti/' and (text() = 'KONTAKTI' or . = 'KONTAKTI')]</value>
      <webElementGuid>f8504497-28f4-4b49-971b-0cb33c6c6278</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
